### ISSUE TITLE
项目本地更新脚手架问题

### ISSUE THREAD

**Issue by vegawong** [steamerjs/steamer-plugin-kit#4]
项目本地更新脚手架时，没有按照.steamer/{starterkitName}.js里面的files约定更新文件，而且把脚手架里面所有文件都更新到项目里面。待优化更新。

![image](https://user-images.githubusercontent.com/17271745/40650783-a38747e8-6366-11e8-94c4-21667cc1d4b1.png)

**Comment by lcxfs1991** [comment]
fix
