### ISSUE TITLE
update global版本异常

### ISSUE THREAD

**Issue by vegawong** [steamerjs/steamer-plugin-kit#6]
这里记录一下，当用-u -g更新已经是最新版本的starterkit的时候， 会添加多余的版本号，

![qq20180614-102312](https://user-images.githubusercontent.com/17271745/41388119-0b3ca40c-6fbd-11e8-915e-94261a8062f0.png)

稍后会发起对应的pr

**Comment by lcxfs1991** [comment]
赞

**Comment by vegawong** [comment]
跟pr #7 相关
